package io.ybr.postgresbulk.starter.jdbc.it;

import static org.assertj.core.api.Assertions.assertThat;
import static org.assertj.core.api.Assertions.assertThatThrownBy;

import io.ybr.postgresbulk.core.BulkException;
import io.ybr.postgresbulk.core.BulkInsertOptions;
import io.ybr.postgresbulk.core.BulkWriteResult;
import io.ybr.postgresbulk.core.metadata.BulkKeyMetadata;
import io.ybr.postgresbulk.core.metadata.ColumnMetadata;
import io.ybr.postgresbulk.core.metadata.TableName;
import io.ybr.postgresbulk.springdata.jdbc.SpringDataJdbcEntityMetadataResolver;
import java.sql.SQLException;
import java.util.List;
import java.util.concurrent.ExecutorService;
import java.util.concurrent.Executors;
import java.util.concurrent.Future;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.boot.test.context.SpringBootTest;
import org.springframework.dao.InvalidDataAccessApiUsageException;
import org.springframework.jdbc.core.JdbcOperations;
import org.springframework.test.context.DynamicPropertyRegistry;
import org.springframework.test.context.DynamicPropertySource;
import org.springframework.transaction.PlatformTransactionManager;
import org.springframework.transaction.TransactionDefinition;
import org.springframework.transaction.support.TransactionTemplate;
import org.testcontainers.junit.jupiter.Container;
import org.testcontainers.junit.jupiter.Testcontainers;
import org.testcontainers.postgresql.PostgreSQLContainer;

@SpringBootTest
@Testcontainers
class JdbcStarterSmokeIT {

  @Container
  private static final PostgreSQLContainer POSTGRES =
      new PostgreSQLContainer("postgres:" + System.getProperty("postgres.version"))
          .withDatabaseName("postgres_bulk_jdbc_starter")
          .withUsername("postgres_bulk_jdbc_starter")
          .withPassword("postgres_bulk_jdbc_starter");

  @Autowired private ProductRepository products;
  @Autowired private GeneratedProductRepository generatedProducts;
  @Autowired private SpringDataJdbcEntityMetadataResolver metadataResolver;
  @Autowired private JdbcOperations jdbc;
  @Autowired private PlatformTransactionManager transactionManager;

  @DynamicPropertySource
  static void databaseProperties(DynamicPropertyRegistry registry) {
    registry.add("spring.datasource.url", POSTGRES::getJdbcUrl);
    registry.add("spring.datasource.username", POSTGRES::getUsername);
    registry.add("spring.datasource.password", POSTGRES::getPassword);
    registry.add("spring.datasource.hikari.maximum-pool-size", () -> "4");
    registry.add("spring.datasource.hikari.minimum-idle", () -> "0");
  }

  @BeforeEach
  void resetSchema() {
    jdbc.execute(
        "CREATE TABLE IF NOT EXISTS j6_products ("
            + "id bigint PRIMARY KEY, sku text NOT NULL UNIQUE, category text NOT NULL, "
            + "amount numeric(19,2) NOT NULL, address_city text, address_postal_code text)");
    jdbc.execute(
        "CREATE TABLE IF NOT EXISTS j6_generated_products ("
            + "id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, code text NOT NULL UNIQUE)");
    jdbc.execute("TRUNCATE j6_products, j6_generated_products RESTART IDENTITY");
    for (String schema : List.of("ms6_jdbc_a", "ms6_jdbc_b", "ms6_jdbc_c", "MS6 JDBC Quoted")) {
      jdbc.execute("CREATE SCHEMA IF NOT EXISTS \"" + schema + "\"");
      jdbc.execute(
          "CREATE TABLE IF NOT EXISTS \""
              + schema
              + "\".j6_products (LIKE public.j6_products INCLUDING ALL)");
      jdbc.execute("TRUNCATE \"" + schema + "\".j6_products");
    }
  }

  @Test
  void starterComposesDefaultAndThreeRuntimeSchemasWithIsolation() {
    TableName a = target("ms6_jdbc_a");
    TableName b = target("ms6_jdbc_b");
    TableName c = target("ms6_jdbc_c");

    products.bulkInsert(List.of(product(400L, "DEFAULT", "tools", "1", "Madrid")));
    products.bulkInsert(a, List.of(product(401L, "A", "tools", "1", "Madrid")));
    products.bulkInsert(b, List.of(product(402L, "B", "tools", "1", "Madrid")));
    products.bulkInsert(c, List.of(product(403L, "C", "tools", "1", "Madrid")));

    assertThat(products.findAllByBulkKey(List.of("A", "B"), skuMetadata(), a))
        .extracting(Product::sku)
        .containsExactly("A");
    assertThat(products.findAllByBulkKey(List.of("A", "B"), skuMetadata(), b))
        .extracting(Product::sku)
        .containsExactly("B");
    assertThat(jdbc.queryForObject("SELECT count(*) FROM ms6_jdbc_c.j6_products", Long.class))
        .isEqualTo(1L);
    assertThat(products.count()).isEqualTo(1L);
  }

  @Test
  void starterPreservesTargetTransactionsQuotingAndConflictRules() {
    TransactionTemplate transaction = new TransactionTemplate(transactionManager);
    transaction.executeWithoutResult(
        status -> {
          products.bulkInsert(
              target("ms6_jdbc_a"), List.of(product(410L, "COMMIT-A", "tools", "1", "Madrid")));
          products.bulkInsert(
              target("ms6_jdbc_b"), List.of(product(411L, "COMMIT-B", "tools", "1", "Madrid")));
        });
    transaction.executeWithoutResult(
        status -> {
          products.bulkInsert(
              target("ms6_jdbc_a"), List.of(product(412L, "ROLLBACK-A", "tools", "1", "Madrid")));
          products.bulkInsert(
              target("ms6_jdbc_b"), List.of(product(413L, "ROLLBACK-B", "tools", "1", "Madrid")));
          status.setRollbackOnly();
        });
    TransactionTemplate requiresNew = new TransactionTemplate(transactionManager);
    requiresNew.setPropagationBehavior(TransactionDefinition.PROPAGATION_REQUIRES_NEW);
    transaction.executeWithoutResult(
        status -> {
          products.bulkInsert(
              target("ms6_jdbc_a"),
              List.of(product(416L, "OUTER-ROLLBACK", "tools", "1", "Madrid")));
          requiresNew.executeWithoutResult(
              inner ->
                  products.bulkInsert(
                      target("ms6_jdbc_b"),
                      List.of(product(417L, "INNER-COMMIT", "tools", "1", "Madrid"))));
          status.setRollbackOnly();
        });

    TableName quoted = target("MS6 JDBC Quoted");
    products.bulkInsert(quoted, List.of(product(414L, "QUOTED", "tools", "1", "Madrid")));
    assertThat(products.findAllByBulkKey(List.of("QUOTED"), skuMetadata(), quoted)).hasSize(1);
    assertThat(jdbc.queryForObject("SELECT count(*) FROM ms6_jdbc_a.j6_products", Long.class))
        .isEqualTo(1L);
    assertThat(jdbc.queryForObject("SELECT count(*) FROM ms6_jdbc_b.j6_products", Long.class))
        .isEqualTo(2L);

    assertThatThrownBy(
            () ->
                products.bulkInsert(
                    TableName.of("ms6_jdbc_a", "wrong_table"),
                    List.of(product(415L, "CONFLICT", "tools", "1", "Madrid"))))
        .isInstanceOf(IllegalArgumentException.class);

    assertThatThrownBy(
            () ->
                products.bulkInsert(
                    TableName.of("ms6_jdbc_missing", "j6_products"),
                    List.of(product(418L, "MISSING", "tools", "1", "Madrid"))))
        .isInstanceOf(BulkException.class)
        .satisfies(
            failure ->
                assertThat(findCause(failure, SQLException.class).getSQLState())
                    .isEqualTo("3F000"));

    TransactionTemplate readOnly = new TransactionTemplate(transactionManager);
    readOnly.setReadOnly(true);
    assertThatThrownBy(
            () ->
                readOnly.executeWithoutResult(
                    status ->
                        products.bulkInsert(
                            target("ms6_jdbc_a"),
                            List.of(product(419L, "READ-ONLY-TARGET", "tools", "1", "Madrid")))))
        .isInstanceOf(InvalidDataAccessApiUsageException.class);
  }

  @Test
  void starterRunsConcurrentTargetsThroughOneRepositoryProxy() throws Exception {
    ExecutorService executor = Executors.newFixedThreadPool(2);
    try {
      Future<?> a =
          executor.submit(
              () ->
                  products.bulkInsert(
                      target("ms6_jdbc_a"),
                      List.of(product(420L, "CONCURRENT-A", "tools", "1", "Madrid"))));
      Future<?> b =
          executor.submit(
              () ->
                  products.bulkInsert(
                      target("ms6_jdbc_b"),
                      List.of(product(421L, "CONCURRENT-B", "tools", "1", "Madrid"))));
      a.get();
      b.get();
    } finally {
      executor.shutdownNow();
    }

    assertThat(jdbc.queryForObject("SELECT count(*) FROM ms6_jdbc_a.j6_products", Long.class))
        .isEqualTo(1L);
    assertThat(jdbc.queryForObject("SELECT count(*) FROM ms6_jdbc_b.j6_products", Long.class))
        .isEqualTo(1L);
  }

  @Test
  void starterDiscoversFragmentAndSupportsDefaultAndExplicitBatches() {
    assertThat(metadataResolver).isNotNull();

    BulkWriteResult defaultResult =
        products.bulkInsert(
            List.of(
                product(1L, "SKU-1", "tools", "10.50", "Madrid"),
                product(2L, "SKU-2", "tools", "20.25", "Havana")));
    BulkWriteResult explicitResult =
        products.bulkInsert(
            List.of(
                product(3L, "SKU-3", "books", "30.00", "Seville"),
                product(4L, "SKU-4", "books", "40.00", "Toledo")),
            BulkInsertOptions.ofBatchSize(1));

    assertThat(defaultResult).isEqualTo(new BulkWriteResult(2, 1));
    assertThat(explicitResult).isEqualTo(new BulkWriteResult(2, 2));
    assertThat(jdbc.queryForObject("SELECT count(*) FROM j6_products", Long.class)).isEqualTo(4L);
  }

  @Test
  void preservesAssignedAndGeneratedIdentifierPolicies() {
    products.bulkInsert(List.of(product(90L, "ASSIGNED", "tools", "1.00", "Madrid")));
    GeneratedProduct generated = new GeneratedProduct(null, "GENERATED");

    assertThat(generatedProducts.bulkInsert(List.of(generated)))
        .isEqualTo(new BulkWriteResult(1, 1));
    assertThat(generated.id()).isNull();
    assertThat(
            jdbc.queryForObject(
                "SELECT id FROM j6_generated_products WHERE code = 'GENERATED'", Long.class))
        .isPositive();
    assertThat(jdbc.queryForObject("SELECT id FROM j6_products WHERE sku = 'ASSIGNED'", Long.class))
        .isEqualTo(90L);
  }

  @Test
  void materializesSimpleAndCompositeLookupsWithConvertersAndEmbeddedValues() {
    Product hammer = product(10L, "HAMMER", "tools", "12.75", "Madrid");
    Product novel = product(11L, "NOVEL", "books", "8.25", "Havana");
    products.bulkInsert(List.of(hammer, novel));

    BulkKeyMetadata<String> simple =
        BulkKeyMetadata.of(
            String.class, List.of(ColumnMetadata.of("sku", String.class, value -> value)));
    BulkKeyMetadata<ProductKey> composite =
        BulkKeyMetadata.of(
            ProductKey.class,
            List.of(
                ColumnMetadata.of("sku", String.class, ProductKey::sku),
                ColumnMetadata.of("category", String.class, ProductKey::category)));

    assertThat(products.findAllByBulkKey(List.of("HAMMER", "missing", "HAMMER"), simple))
        .containsExactly(hammer);
    assertThat(
            products.findAllByBulkKey(
                List.of(new ProductKey("NOVEL", "books"), new ProductKey("HAMMER", "wrong")),
                composite))
        .containsExactly(novel);
  }

  @Test
  void honorsRequiredRollbackAndReadOnlyTransactions() {
    TransactionTemplate rollback = new TransactionTemplate(transactionManager);
    rollback.executeWithoutResult(
        status -> {
          products.bulkInsert(List.of(product(20L, "ROLLBACK", "tools", "1", "Madrid")));
          status.setRollbackOnly();
        });

    TransactionTemplate readOnly = new TransactionTemplate(transactionManager);
    readOnly.setReadOnly(true);

    assertThat(jdbc.queryForObject("SELECT count(*) FROM j6_products", Long.class)).isZero();
    assertThatThrownBy(
            () ->
                readOnly.executeWithoutResult(
                    status ->
                        products.bulkInsert(
                            List.of(product(21L, "READ-ONLY", "tools", "1", "Madrid")))))
        .isInstanceOf(InvalidDataAccessApiUsageException.class);
  }

  @Test
  void honorsRequiresNewAndNestedBoundaries() {
    TransactionTemplate outer = new TransactionTemplate(transactionManager);
    TransactionTemplate requiresNew = new TransactionTemplate(transactionManager);
    requiresNew.setPropagationBehavior(TransactionDefinition.PROPAGATION_REQUIRES_NEW);

    outer.executeWithoutResult(
        status -> {
          products.bulkInsert(List.of(product(30L, "OUTER", "tools", "1", "Madrid")));
          requiresNew.executeWithoutResult(
              inner -> products.bulkInsert(List.of(product(31L, "INNER", "tools", "1", "Madrid"))));
          status.setRollbackOnly();
        });

    TransactionTemplate nestedOuter = new TransactionTemplate(transactionManager);
    TransactionTemplate nested = new TransactionTemplate(transactionManager);
    nested.setPropagationBehavior(TransactionDefinition.PROPAGATION_NESTED);
    nestedOuter.executeWithoutResult(
        status -> {
          products.bulkInsert(List.of(product(32L, "NESTED-OUTER", "tools", "1", "Madrid")));
          nested.executeWithoutResult(
              inner -> {
                products.bulkInsert(List.of(product(33L, "NESTED-INNER", "tools", "1", "Madrid")));
                inner.setRollbackOnly();
              });
        });

    assertThat(jdbc.queryForList("SELECT sku FROM j6_products ORDER BY sku", String.class))
        .containsExactly("INNER", "NESTED-OUTER");
  }

  private static Product product(long id, String sku, String category, String amount, String city) {
    return new Product(id, sku, category, new Money(amount), new Address(city, "28001"));
  }

  private static BulkKeyMetadata<String> skuMetadata() {
    return BulkKeyMetadata.of(
        String.class, List.of(ColumnMetadata.of("sku", String.class, value -> value)));
  }

  private static TableName target(String schema) {
    return TableName.of(schema, "j6_products");
  }

  private static <T extends Throwable> T findCause(Throwable failure, Class<T> type) {
    for (Throwable current = failure; current != null; current = current.getCause()) {
      if (type.isInstance(current)) {
        return type.cast(current);
      }
    }
    return null;
  }
}
