package io.ybr.postgresbulk.starter.jdbc.it;

import static org.assertj.core.api.Assertions.assertThat;
import static org.assertj.core.api.Assertions.assertThatThrownBy;

import io.ybr.postgresbulk.core.BulkInsertOptions;
import io.ybr.postgresbulk.core.BulkWriteResult;
import io.ybr.postgresbulk.core.metadata.BulkKeyMetadata;
import io.ybr.postgresbulk.core.metadata.ColumnMetadata;
import io.ybr.postgresbulk.springdata.jdbc.SpringDataJdbcEntityMetadataResolver;
import java.util.List;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.boot.test.context.SpringBootTest;
import org.springframework.dao.InvalidDataAccessApiUsageException;
import org.springframework.jdbc.core.JdbcOperations;
import org.springframework.test.context.DynamicPropertyRegistry;
import org.springframework.test.context.DynamicPropertySource;
import org.springframework.transaction.PlatformTransactionManager;
import org.springframework.transaction.TransactionDefinition;
import org.springframework.transaction.support.TransactionTemplate;
import org.testcontainers.junit.jupiter.Container;
import org.testcontainers.junit.jupiter.Testcontainers;
import org.testcontainers.postgresql.PostgreSQLContainer;

@SpringBootTest
@Testcontainers
class JdbcStarterSmokeIT {

  @Container
  private static final PostgreSQLContainer POSTGRES =
      new PostgreSQLContainer("postgres:" + System.getProperty("postgres.version"))
          .withDatabaseName("postgres_bulk_jdbc_starter")
          .withUsername("postgres_bulk_jdbc_starter")
          .withPassword("postgres_bulk_jdbc_starter");

  @Autowired private ProductRepository products;
  @Autowired private GeneratedProductRepository generatedProducts;
  @Autowired private SpringDataJdbcEntityMetadataResolver metadataResolver;
  @Autowired private JdbcOperations jdbc;
  @Autowired private PlatformTransactionManager transactionManager;

  @DynamicPropertySource
  static void databaseProperties(DynamicPropertyRegistry registry) {
    registry.add("spring.datasource.url", POSTGRES::getJdbcUrl);
    registry.add("spring.datasource.username", POSTGRES::getUsername);
    registry.add("spring.datasource.password", POSTGRES::getPassword);
    registry.add("spring.datasource.hikari.maximum-pool-size", () -> "4");
    registry.add("spring.datasource.hikari.minimum-idle", () -> "0");
  }

  @BeforeEach
  void resetSchema() {
    jdbc.execute(
        "CREATE TABLE IF NOT EXISTS j6_products ("
            + "id bigint PRIMARY KEY, sku text NOT NULL UNIQUE, category text NOT NULL, "
            + "amount numeric(19,2) NOT NULL, address_city text, address_postal_code text)");
    jdbc.execute(
        "CREATE TABLE IF NOT EXISTS j6_generated_products ("
            + "id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, code text NOT NULL UNIQUE)");
    jdbc.execute("TRUNCATE j6_products, j6_generated_products RESTART IDENTITY");
  }

  @Test
  void starterDiscoversFragmentAndSupportsDefaultAndExplicitBatches() {
    assertThat(metadataResolver).isNotNull();

    BulkWriteResult defaultResult =
        products.bulkInsert(
            List.of(
                product(1L, "SKU-1", "tools", "10.50", "Madrid"),
                product(2L, "SKU-2", "tools", "20.25", "Havana")));
    BulkWriteResult explicitResult =
        products.bulkInsert(
            List.of(
                product(3L, "SKU-3", "books", "30.00", "Seville"),
                product(4L, "SKU-4", "books", "40.00", "Toledo")),
            BulkInsertOptions.ofBatchSize(1));

    assertThat(defaultResult).isEqualTo(new BulkWriteResult(2, 1));
    assertThat(explicitResult).isEqualTo(new BulkWriteResult(2, 2));
    assertThat(jdbc.queryForObject("SELECT count(*) FROM j6_products", Long.class)).isEqualTo(4L);
  }

  @Test
  void preservesAssignedAndGeneratedIdentifierPolicies() {
    products.bulkInsert(List.of(product(90L, "ASSIGNED", "tools", "1.00", "Madrid")));
    GeneratedProduct generated = new GeneratedProduct(null, "GENERATED");

    assertThat(generatedProducts.bulkInsert(List.of(generated)))
        .isEqualTo(new BulkWriteResult(1, 1));
    assertThat(generated.id()).isNull();
    assertThat(
            jdbc.queryForObject(
                "SELECT id FROM j6_generated_products WHERE code = 'GENERATED'", Long.class))
        .isPositive();
    assertThat(jdbc.queryForObject("SELECT id FROM j6_products WHERE sku = 'ASSIGNED'", Long.class))
        .isEqualTo(90L);
  }

  @Test
  void materializesSimpleAndCompositeLookupsWithConvertersAndEmbeddedValues() {
    Product hammer = product(10L, "HAMMER", "tools", "12.75", "Madrid");
    Product novel = product(11L, "NOVEL", "books", "8.25", "Havana");
    products.bulkInsert(List.of(hammer, novel));

    BulkKeyMetadata<String> simple =
        BulkKeyMetadata.of(
            String.class, List.of(ColumnMetadata.of("sku", String.class, value -> value)));
    BulkKeyMetadata<ProductKey> composite =
        BulkKeyMetadata.of(
            ProductKey.class,
            List.of(
                ColumnMetadata.of("sku", String.class, ProductKey::sku),
                ColumnMetadata.of("category", String.class, ProductKey::category)));

    assertThat(products.findAllByBulkKey(List.of("HAMMER", "missing", "HAMMER"), simple))
        .containsExactly(hammer);
    assertThat(
            products.findAllByBulkKey(
                List.of(new ProductKey("NOVEL", "books"), new ProductKey("HAMMER", "wrong")),
                composite))
        .containsExactly(novel);
  }

  @Test
  void honorsRequiredRollbackAndReadOnlyTransactions() {
    TransactionTemplate rollback = new TransactionTemplate(transactionManager);
    rollback.executeWithoutResult(
        status -> {
          products.bulkInsert(List.of(product(20L, "ROLLBACK", "tools", "1", "Madrid")));
          status.setRollbackOnly();
        });

    TransactionTemplate readOnly = new TransactionTemplate(transactionManager);
    readOnly.setReadOnly(true);

    assertThat(jdbc.queryForObject("SELECT count(*) FROM j6_products", Long.class)).isZero();
    assertThatThrownBy(
            () ->
                readOnly.executeWithoutResult(
                    status ->
                        products.bulkInsert(
                            List.of(product(21L, "READ-ONLY", "tools", "1", "Madrid")))))
        .isInstanceOf(InvalidDataAccessApiUsageException.class);
  }

  @Test
  void honorsRequiresNewAndNestedBoundaries() {
    TransactionTemplate outer = new TransactionTemplate(transactionManager);
    TransactionTemplate requiresNew = new TransactionTemplate(transactionManager);
    requiresNew.setPropagationBehavior(TransactionDefinition.PROPAGATION_REQUIRES_NEW);

    outer.executeWithoutResult(
        status -> {
          products.bulkInsert(List.of(product(30L, "OUTER", "tools", "1", "Madrid")));
          requiresNew.executeWithoutResult(
              inner -> products.bulkInsert(List.of(product(31L, "INNER", "tools", "1", "Madrid"))));
          status.setRollbackOnly();
        });

    TransactionTemplate nestedOuter = new TransactionTemplate(transactionManager);
    TransactionTemplate nested = new TransactionTemplate(transactionManager);
    nested.setPropagationBehavior(TransactionDefinition.PROPAGATION_NESTED);
    nestedOuter.executeWithoutResult(
        status -> {
          products.bulkInsert(List.of(product(32L, "NESTED-OUTER", "tools", "1", "Madrid")));
          nested.executeWithoutResult(
              inner -> {
                products.bulkInsert(List.of(product(33L, "NESTED-INNER", "tools", "1", "Madrid")));
                inner.setRollbackOnly();
              });
        });

    assertThat(jdbc.queryForList("SELECT sku FROM j6_products ORDER BY sku", String.class))
        .containsExactly("INNER", "NESTED-OUTER");
  }

  private static Product product(long id, String sku, String category, String amount, String city) {
    return new Product(id, sku, category, new Money(amount), new Address(city, "28001"));
  }
}
