spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres_bulk_example
    username: postgres
    password: postgres
  jpa:
    hibernate:
      ddl-auto: create-drop
    open-in-view: false
