package io.ybr.postgresbulk.springdata.jdbc.repository;

import static org.junit.jupiter.api.Assertions.assertEquals;
import static org.junit.jupiter.api.Assertions.assertNull;
import static org.junit.jupiter.api.Assertions.assertThrows;

import com.zaxxer.hikari.HikariConfig;
import com.zaxxer.hikari.HikariDataSource;
import io.ybr.postgresbulk.core.BulkException;
import io.ybr.postgresbulk.core.BulkInsertOptions;
import io.ybr.postgresbulk.core.BulkWriteResult;
import io.ybr.postgresbulk.core.metadata.BulkKeyMetadata;
import io.ybr.postgresbulk.core.metadata.ColumnMetadata;
import io.ybr.postgresbulk.springdata.jdbc.SpringDataJdbcEntityMetadataResolver;
import java.math.BigDecimal;
import java.sql.SQLException;
import java.util.List;
import java.util.UUID;
import java.util.concurrent.CompletableFuture;
import java.util.stream.IntStream;
import javax.sql.DataSource;
import org.junit.jupiter.api.AfterAll;
import org.junit.jupiter.api.BeforeAll;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;
import org.springframework.context.annotation.AnnotationConfigApplicationContext;
import org.springframework.context.annotation.Bean;
import org.springframework.context.annotation.Configuration;
import org.springframework.core.convert.converter.Converter;
import org.springframework.dao.InvalidDataAccessApiUsageException;
import org.springframework.data.annotation.Id;
import org.springframework.data.convert.ReadingConverter;
import org.springframework.data.convert.WritingConverter;
import org.springframework.data.jdbc.core.convert.JdbcConverter;
import org.springframework.data.jdbc.core.convert.JdbcCustomConversions;
import org.springframework.data.jdbc.repository.config.AbstractJdbcConfiguration;
import org.springframework.data.jdbc.repository.config.EnableJdbcRepositories;
import org.springframework.data.relational.core.mapping.Table;
import org.springframework.data.repository.CrudRepository;
import org.springframework.jdbc.core.JdbcOperations;
import org.springframework.jdbc.core.JdbcTemplate;
import org.springframework.jdbc.core.namedparam.NamedParameterJdbcOperations;
import org.springframework.jdbc.core.namedparam.NamedParameterJdbcTemplate;
import org.springframework.jdbc.support.JdbcTransactionManager;
import org.springframework.transaction.PlatformTransactionManager;
import org.springframework.transaction.annotation.EnableTransactionManagement;
import org.springframework.transaction.annotation.Propagation;
import org.springframework.transaction.support.TransactionTemplate;
import org.testcontainers.junit.jupiter.Container;
import org.testcontainers.junit.jupiter.Testcontainers;
import org.testcontainers.postgresql.PostgreSQLContainer;

@Testcontainers
class PostgresBulkJdbcRepositoryIT {

  @Container
  private static final PostgreSQLContainer POSTGRES =
      new PostgreSQLContainer("postgres:" + System.getProperty("postgres.version"))
          .withDatabaseName("postgres_bulk_repository")
          .withUsername("postgres_bulk_repository")
          .withPassword("postgres_bulk_repository");

  private static AnnotationConfigApplicationContext context;
  private static JdbcOperations jdbc;
  private static ProductRepository products;
  private static WarehouseRepository warehouses;
  private static MissingTableRepository missing;
  private static PlatformTransactionManager transactionManager;

  @BeforeAll
  static void createContext() {
    context = new AnnotationConfigApplicationContext(TestConfiguration.class);
    jdbc = context.getBean(JdbcOperations.class);
    products = context.getBean(ProductRepository.class);
    warehouses = context.getBean(WarehouseRepository.class);
    missing = context.getBean(MissingTableRepository.class);
    transactionManager = context.getBean(PlatformTransactionManager.class);
    jdbc.execute(
        "CREATE TABLE repository_products ("
            + "id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, "
            + "code text NOT NULL UNIQUE, category text NOT NULL, amount numeric(12,2))");
    jdbc.execute(
        "CREATE TABLE repository_warehouses (id uuid PRIMARY KEY, label text NOT NULL UNIQUE)");
  }

  @BeforeEach
  void cleanTables() {
    jdbc.execute("TRUNCATE repository_products, repository_warehouses RESTART IDENTITY");
  }

  @AfterAll
  static void closeContext() {
    if (context != null) {
      context.close();
    }
  }

  @Test
  void discoversExternalFragmentAndInsertsWithDefaultAndExplicitOptions() {
    Product generated = new Product(null, "generated", "tools", new Money("12.50"));
    assertEquals(new BulkWriteResult(1, 1), products.bulkInsert(List.of(generated)));
    assertNull(generated.id());

    List<Product> assigned =
        List.of(
            new Product(20L, "assigned-a", "books", new Money("3.25")),
            new Product(21L, "assigned-b", "books", new Money("4.75")));
    assertEquals(
        new BulkWriteResult(2, 2), products.bulkInsert(assigned, BulkInsertOptions.ofBatchSize(1)));

    assertEquals(3L, jdbc.queryForObject("SELECT count(*) FROM repository_products", Long.class));
    assertEquals(
        new BigDecimal("12.50"),
        jdbc.queryForObject(
            "SELECT amount FROM repository_products WHERE code = 'generated'", BigDecimal.class));
  }

  @Test
  void looksUpSimpleAndCompositeKeysWithConfiguredConverters() {
    products.bulkInsert(
        List.of(
            new Product(1L, "hammer", "tools", new Money("10.00")),
            new Product(2L, "saw", "tools", new Money("20.00")),
            new Product(3L, "novel", "books", new Money("30.00"))));

    BulkKeyMetadata<String> simple =
        BulkKeyMetadata.of(
            String.class, List.of(ColumnMetadata.of("code", String.class, value -> value)));
    assertEquals(
        List.of("hammer", "saw"),
        products.findAllByBulkKey(List.of("saw", "missing", "hammer", "saw"), simple).stream()
            .map(Product::code)
            .sorted()
            .toList());

    BulkKeyMetadata<ProductKey> composite =
        BulkKeyMetadata.of(
            ProductKey.class,
            List.of(
                ColumnMetadata.of("code", String.class, ProductKey::code),
                ColumnMetadata.of("category", String.class, ProductKey::category)));
    List<Product> matches =
        products.findAllByBulkKey(
            List.of(new ProductKey("novel", "books"), new ProductKey("hammer", "wrong")),
            composite);
    assertEquals(List.of(new Product(3L, "novel", "books", new Money("30.00"))), matches);
  }

  @Test
  void emptyInputsDoNotNeedAPhysicalTable() {
    assertEquals(BulkWriteResult.empty(), missing.bulkInsert(List.of()));
    assertEquals(
        List.of(),
        missing.findAllByBulkKey(
            List.of(),
            BulkKeyMetadata.of(
                String.class, List.of(ColumnMetadata.of("value", String.class, value -> value)))));
  }

  @Test
  void preservesRollbackReadOnlyMixedIdAndSqlFailureContracts() {
    TransactionTemplate rollback = new TransactionTemplate(transactionManager);
    rollback.executeWithoutResult(
        status -> {
          products.bulkInsert(List.of(new Product(10L, "rollback", "tools", new Money("1"))));
          status.setRollbackOnly();
        });
    assertEquals(
        0L,
        jdbc.queryForObject(
            "SELECT count(*) FROM repository_products WHERE code = 'rollback'", Long.class));

    TransactionTemplate readOnly = new TransactionTemplate(transactionManager);
    readOnly.setReadOnly(true);
    assertThrows(
        InvalidDataAccessApiUsageException.class,
        () ->
            readOnly.executeWithoutResult(
                status ->
                    products.bulkInsert(
                        List.of(new Product(11L, "read-only", "tools", new Money("1"))))));

    assertThrows(
        InvalidDataAccessApiUsageException.class,
        () ->
            products.bulkInsert(
                List.of(
                    new Product(null, "generated", "tools", new Money("1")),
                    new Product(12L, "assigned", "tools", new Money("1")))));

    products.bulkInsert(List.of(new Product(13L, "duplicate", "tools", new Money("1"))));
    BulkException duplicate =
        assertThrows(
            BulkException.class,
            () ->
                products.bulkInsert(
                    List.of(new Product(14L, "duplicate", "tools", new Money("1")))));
    assertEquals("23505", sqlState(duplicate));
  }

  @Test
  void repositoryCallsHonorRequiresNewBoundaries() {
    TransactionTemplate outer = new TransactionTemplate(transactionManager);
    TransactionTemplate inner = new TransactionTemplate(transactionManager);
    inner.setPropagationBehavior(Propagation.REQUIRES_NEW.value());

    outer.executeWithoutResult(
        status -> {
          products.bulkInsert(List.of(new Product(30L, "outer", "tools", new Money("1.00"))));
          inner.executeWithoutResult(
              innerStatus ->
                  products.bulkInsert(
                      List.of(new Product(31L, "inner", "tools", new Money("2.00")))));
          status.setRollbackOnly();
        });

    assertEquals(
        List.of("inner"),
        jdbc.queryForList("SELECT code FROM repository_products ORDER BY code", String.class));
  }

  @Test
  void isolatesMultipleRepositoryDomainTypesAndConcurrentCalls() {
    UUID warehouseId = UUID.fromString("c1e97a9f-1860-4d3e-a04e-3a6a6ea68131");
    assertEquals(
        new BulkWriteResult(1, 1),
        warehouses.bulkInsert(List.of(new Warehouse(warehouseId, "central"))));

    List<CompletableFuture<Void>> calls =
        IntStream.range(0, 6)
            .mapToObj(
                index ->
                    CompletableFuture.runAsync(
                        () ->
                            products.bulkInsert(
                                List.of(
                                    new Product(
                                        100L + index,
                                        "concurrent-" + index,
                                        "tools",
                                        new Money("1.00"))))))
            .toList();
    CompletableFuture.allOf(calls.toArray(CompletableFuture[]::new)).join();

    assertEquals(6L, jdbc.queryForObject("SELECT count(*) FROM repository_products", Long.class));
    assertEquals(1L, jdbc.queryForObject("SELECT count(*) FROM repository_warehouses", Long.class));
  }

  private static String sqlState(Throwable failure) {
    Throwable current = failure;
    while (current != null) {
      if (current instanceof SQLException sqlException && sqlException.getSQLState() != null) {
        return sqlException.getSQLState();
      }
      current = current.getCause();
    }
    throw new AssertionError("No SQLException with SQLState", failure);
  }

  interface ProductRepository
      extends CrudRepository<Product, Long>, PostgresBulkJdbcRepository<Product> {}

  interface WarehouseRepository
      extends CrudRepository<Warehouse, UUID>, PostgresBulkJdbcRepository<Warehouse> {}

  interface MissingTableRepository
      extends CrudRepository<MissingTable, Long>, PostgresBulkJdbcRepository<MissingTable> {}

  @Table("repository_products")
  record Product(@Id Long id, String code, String category, Money amount) {}

  @Table("repository_warehouses")
  record Warehouse(@Id UUID id, String label) {}

  @Table("table_that_does_not_exist")
  record MissingTable(@Id Long id, String value) {}

  record ProductKey(String code, String category) {}

  record Money(BigDecimal value) {
    Money(String value) {
      this(new BigDecimal(value));
    }
  }

  @WritingConverter
  enum MoneyWritingConverter implements Converter<Money, BigDecimal> {
    INSTANCE;

    @Override
    public BigDecimal convert(Money source) {
      return source.value();
    }
  }

  @ReadingConverter
  enum MoneyReadingConverter implements Converter<BigDecimal, Money> {
    INSTANCE;

    @Override
    public Money convert(BigDecimal source) {
      return new Money(source);
    }
  }

  @Configuration(proxyBeanMethods = false)
  @EnableTransactionManagement
  @EnableJdbcRepositories(
      basePackageClasses = PostgresBulkJdbcRepositoryIT.class,
      considerNestedRepositories = true)
  static class TestConfiguration extends AbstractJdbcConfiguration {

    @Bean(destroyMethod = "close")
    DataSource dataSource() {
      HikariConfig pool = new HikariConfig();
      pool.setJdbcUrl(POSTGRES.getJdbcUrl());
      pool.setUsername(POSTGRES.getUsername());
      pool.setPassword(POSTGRES.getPassword());
      pool.setMaximumPoolSize(8);
      pool.setMinimumIdle(0);
      return new HikariDataSource(pool);
    }

    @Bean
    NamedParameterJdbcOperations namedParameterJdbcOperations(DataSource dataSource) {
      return new NamedParameterJdbcTemplate(dataSource);
    }

    @Bean
    JdbcOperations jdbcOperations(DataSource dataSource) {
      return new JdbcTemplate(dataSource);
    }

    @Bean
    PlatformTransactionManager transactionManager(DataSource dataSource) {
      return new JdbcTransactionManager(dataSource);
    }

    @Bean
    SpringDataJdbcEntityMetadataResolver postgresBulkJdbcMetadataResolver(
        JdbcConverter converter, JdbcCustomConversions conversions) {
      return new SpringDataJdbcEntityMetadataResolver(converter, conversions);
    }

    @Override
    protected List<?> userConverters() {
      return List.of(MoneyWritingConverter.INSTANCE, MoneyReadingConverter.INSTANCE);
    }
  }
}
